context("kbodatamining")

test_that("batter_boxscore work", {
  lee_boxscore <- batter_boxscore(hanhwa_batter_2018,"이용규")
  expect_equal(nrow(lee_boxscore),1)
  expect_equal(ncol(lee_boxscore),28)
  lee_boxscore_2018 <- batter_boxscore(hanhwa_batter_2018,"이용규",yearly=2018)
  expect_equal(nrow(lee_boxscore_2018),1)
  expect_equal(ncol(lee_boxscore_2018),28)
  lee_boxscore_2018_05 <- batter_boxscore(hanhwa_batter_2018,"이용규",yearly=2018,monthly = "05")
  expect_equal(nrow(lee_boxscore_2018_05),1)
  expect_equal(ncol(lee_boxscore_2018_05),28)
  team_boxscore <- batter_boxscore(hanhwa_batter_2018,"한화")
  expect_equal(nrow(team_boxscore),1)
  expect_equal(ncol(team_boxscore),27)
})

test_that("pitcher_boxscore work", {
  jung_boxscore <- pitcher_boxscore(hanhwa_pitcher_2018,"정우람")
  expect_equal(nrow(jung_boxscore),1)
  expect_equal(ncol(jung_boxscore),28)
  jung_boxscore_2018 <- pitcher_boxscore(hanhwa_pitcher_2018,"정우람",yearly=2018)
  expect_equal(nrow(jung_boxscore_2018),1)
  expect_equal(ncol(jung_boxscore_2018),28)
  jung_boxscore_2018_05 <- pitcher_boxscore(hanhwa_pitcher_2018,"정우람",yearly=2018,monthly = "05")
  expect_equal(nrow(jung_boxscore_2018_05),1)
  expect_equal(ncol(jung_boxscore_2018_05),28)
  team_boxscore <- pitcher_boxscore(hanhwa_pitcher_2018,"한화")
  expect_equal(nrow(team_boxscore),1)
  expect_equal(ncol(team_boxscore),27)
  })
